modLoader = "kotori_scala"
loaderVersion = "[3.3.0,)"
issueTrackerURL = "https://github.com/bdew-minecraft/generators/issues"
license = "MIT"

[[mods]]
modId = "technobauble"
version = "${file.jarVersion}"
displayName = "Technobauble"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/technobauble"
authors = "bdew"
description = '''
This mod that adds various baubles/curios
'''

[[dependencies.technobauble]]
modId = "forge"
mandatory = true
versionRange = "[47.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.technobauble]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.technobauble]]
modId = "bdlib"
mandatory = true
versionRange = "[1.27.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.technobauble]]
modId = "curios"
mandatory = true
versionRange = "[5.2.0-beta.3,)"
ordering = "NONE"
side = "BOTH"

