modLoader = "kotori_scala"
loaderVersion = "[2.13.10,2.14.0)"
issueTrackerURL = "https://github.com/bdew-minecraft/generators/issues"
license = "MIT"

[[mods]]
modId = "technobauble"
version = "${file.jarVersion}"
displayName = "Technobauble"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/technobauble"
authors = "bdew"
description = '''
This mod that adds various baubles/curios
'''

[[dependencies.technobauble]]
modId = "forge"
mandatory = true
versionRange = "[44.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.technobauble]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.technobauble]]
modId = "bdlib"
mandatory = true
versionRange = "[1.26.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.technobauble]]
modId = "curios"
mandatory = true
versionRange = "[1.19-5.1,)"
ordering = "NONE"
side = "BOTH"

